### ISSUE TITLE
PHP pdo code to access encrypted database?

### ISSUE THREAD

**Issue by BlockChainBobC** [kynetiv/php_pdo_sqlcipher#1]
Hey, I saw the info for this project over at the gdg exephp forum... I am trying to use your prebuild php 5.6.15 dll with the latest version of exephp 2018.3 . I was wondering if you have any sample php code that allows connecting to an encrypted database passing the encryption key. I have not been able to find this information for PDO anywhere.

Also, I am not going to be able to build the .dll myself, So I was wondering if you know if the build for php 5.6.15 should be compatible with php 5.6.38 that is included in exephp 2018.3. Any help you can offer would be great... I have been banging my head against a wall for weeks over this.

**Comment by kynetiv** [comment]
Hi, here's a very basic usage [example](https://github.com/kynetiv/php_pdo_sqlcipher/blob/master/examples/USAGE.md), not sure if you saw that. 

As far as compatibility, I haven't tested it with differences in PHP versions. In general I would guess you can use the DLL with version up to the target PHP version, but not above. So with the current built ddl for 5.6, that'd be 5.6.x up to 5.6.15. I'd appreciate knowing what you find if you try that out.

 If I find some time I'll try and build a newer one for the 5.6, otherwise you might need to try building yourself.

**Comment by kynetiv** [comment]
Hi, I've updated the provided DLL's to the latest releases. Let me know if you have issue and good luck.

**Comment by kynetiv** [comment]
One last thing specific to gdg exephp since you mentioned using it. You'll likely need to compile the php_curl dll with your app in order to have the required OpenSSL dll's included with your build. For whatever reason it is the only way to have those bundled `ssleay32.dll` & `libeay32.dll`. 

If you think this should reopen, feel free.
